import "dotenv/config";
export const environmentConfig = {
  LOCAL_PORT: process.env.LOCAL_PORT,
  MONGODB_URI: process.env.MONGODB_URI,
  DATABASE_NAME: process.env.DATABASE_NAME,
  BUILD_MODE: process.env.BUILD_MODE,
  REDIS_URL: process.env.REDIS_URL,
  REDIS_CLOUD_URL: process.env.REDIS_CLOUD_URL,
  LOCAL_URL: process.env.LOCAL_URL,
  DOMAIN_AUTH0: process.env.DOMAIN_AUTH0,
  RENDER_URL: process.env.RENDER_URL,
  AUTH0_AUDIENCE: process.env.AUTH0_AUDIENCE,
  ACCESS_TOKEN_SECRET_SIGNATURE: process.env.ACCESS_TOKEN_SECRET_SIGNATURE,
  ACCESS_TOKEN_TIME_LIFE: process.env.ACCESS_TOKEN_TIME_LIFE,
  REFRESH_TOKEN_SECRET_SIGNATURE: process.env.REFRESH_TOKEN_SECRET_SIGNATURE,
  REFRESH_TOKEN_TIME_LIFE: process.env.REFRESH_TOKEN_TIME_LIFE,

  CLOUDINARY_CLOUD_NAME: process.env.CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY: process.env.CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET: process.env.CLOUDINARY_API_SECRET,

  MONGODB_PRODUCTION_URI: process.env.MONGODB_PRODUCTION_URI,
  DATABASE_NAME_PRODUCTION: process.env.DATABASE_NAME_PRODUCTION,
};
